import { z } from 'zod';
const id = z.string().min(1).max(200);
const text = z.string().max(4000);
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s => Number.isFinite(Date.parse(s+'T12:00:00Z')) && new Date(s + 'T12:00:00Z').toISOString().slice(0, 10) === s, 'Invalid calendar date');
const money = z.number().finite().min(-1e10).max(1e10).refine(n => Math.abs(n * 100 - Math.round(n * 100)) < .0001, 'Use cents');
const positive = money.refine(n => n >= 0, 'Must be nonnegative');
const account = z.object({ id, name: text, institution: text, type: z.enum(['Checking','Savings','Credit card','Loan','Investment','Cash','Other']), balance: money, available: money, creditLimit: positive.optional(), interestRate: z.number().finite().min(0).max(1000).optional(), minimumPayment: positive.optional(), dueDate: date.optional(), source: z.enum(['manual','plaid']), status: z.enum(['connected','manual','attention']), lastSynced: text, archived: z.boolean().optional() });
const transaction = z.object({ id, plaidTransactionId: id.optional(), source: z.enum(['manual','plaid']).optional(), accountId: id, merchant: text, description: text, amount: money, date, category: text, subcategory: text.optional(), type: z.enum(['expense','income','transfer']), pending: z.boolean().optional(), recurring: z.boolean().optional(), excluded: z.boolean().optional(), tags: z.array(text).max(100).optional(), note: text.optional(), confidence: z.number().min(0).max(1).optional(), categorySource: z.enum(['plaid','rule','learned','manual']).optional(), needsReview: z.boolean().optional(), split: z.array(z.object({category: text, amount: positive})).max(100).optional() });
const bucket = z.object({ id, kind: z.enum(['spend','reserve']), name: text, essential: z.boolean(), source: z.enum(['derived','manual','plaid']), category: text.optional(), merchantKey: text.optional(), perCycle: positive.optional(), rollover: z.enum(['sweep','roll']).optional(), amountDue: positive.optional(), scheduledAmount: z.object({ amount: positive, effectiveDate: date }).strict().optional(), dueDate: date.optional(), reserved: positive.optional(), frequency: z.enum(['monthly','weekly','biweekly','annual','one-time']).optional(), autopay: z.boolean().optional(), accountId: text.optional(), linkedDebtAccountId: id.optional() });
const claim = z.object({ id, name: text, kind: z.enum(['purchase','payoff','fund','commitment']), projectId: id.optional(), targetAmount: positive, openEnded: z.boolean().optional(), fundedAmount: positive, rank: z.number().int().nonnegative(), status: z.enum(['active','someday','paused','complete']), horizon: z.enum(['arrival','commitment']), divisible: z.boolean(), delayCost: z.discriminatedUnion('type',[z.object({type:z.literal('none')}),z.object({type:z.literal('interest'),apr:z.number().finite().nonnegative()}),z.object({type:z.literal('deadline'),date})]), protected: z.boolean(), wantBy: date.optional(), pinned: positive.optional(), linkedAccountId: id.optional(), note: text.optional(), url: text.optional() });
const jsonValue: z.ZodType<unknown> = z.lazy(() => z.union([z.string().max(20000), z.number().finite(), z.boolean(), z.null(), z.array(jsonValue).max(20000), z.record(jsonValue)]));
export const workspaceSchema = z.object({
  modelVersion: z.literal(1), revision: z.number().int().nonnegative().optional(),
  profile: z.object({ name: z.string().min(1).max(120), email: z.string().max(254), currency: z.literal('USD'), payFrequency: z.enum(['Weekly','Biweekly','Monthly']), nextPayday: z.union([date,z.literal('')]), takeHomePay: positive, bufferFloor: positive, theme: z.enum(['light','dark','system']), onboardingComplete: z.boolean() }),
  accounts: z.array(account).max(1000), transactions: z.array(transaction).max(50000), buckets: z.array(bucket).max(1000), claims: z.array(claim).max(1000),
  projects: z.array(z.object({id,name:text,description:text.optional(),category:text.optional()})).max(1000),
  cycles: z.array(z.object({id,start:date,end:date,expectedIncome:positive,actualIncome:positive,status:z.enum(['planned','active','closed'])})).max(1000),
  allocations: z.array(z.object({id,cycleId:id,targetType:z.enum(['bucket','claim']),targetId:id,amount:positive,status:z.enum(['proposed','confirmed']),createdAt:text})).max(20000),
  rules: z.array(z.object({id,merchantKey:text,category:text,createdAt:text})).max(10000),
  legacy: z.object({version:z.number().int(),riskTolerance:z.enum(['Cautious','Balanced','Flexible']),budgetingStyle:z.enum(['Paycheck plan','Monthly','Weekly']),paycheckPlan:z.record(z.union([z.number().finite(),text])),recommendations:z.array(jsonValue),memories:z.array(jsonValue),reviews:z.array(jsonValue),notifications:z.array(jsonValue),notificationPreferences:z.record(z.boolean()),goalMeta:z.record(jsonValue),projectMeta:z.record(jsonValue),wishlistMeta:z.record(jsonValue),budgetMeta:z.record(jsonValue),billMeta:z.record(jsonValue),order:z.object({bills:z.array(id),budgets:z.array(id),goals:z.array(id),projects:z.array(id),wishlist:z.array(id)})}),
}).superRefine((w,ctx) => {
  const fail = (message:string) => ctx.addIssue({code:z.ZodIssueCode.custom,message});
  for (const list of [w.accounts,w.transactions,w.buckets,w.claims,w.projects,w.cycles,w.allocations,w.rules]) if(new Set(list.map(x=>x.id)).size !== list.length) fail('Duplicate IDs');
  const accounts = new Set(w.accounts.map(a=>a.id)), claims = new Set(w.claims.map(c=>c.id)), buckets = new Set(w.buckets.map(b=>b.id)), projects = new Set(w.projects.map(p=>p.id));
  for(const t of w.transactions) { if(!accounts.has(t.accountId)) fail('Unknown transaction account'); if(t.split?.length && Math.abs(t.split.reduce((sum,l)=>sum+l.amount,0)-t.amount) > .005) fail('Split must reconcile'); }
  for(const b of w.buckets) if((b.accountId && !accounts.has(b.accountId)) || (b.linkedDebtAccountId && !accounts.has(b.linkedDebtAccountId))) fail('Unknown bill account');
  for(const c of w.claims) if((c.linkedAccountId && !accounts.has(c.linkedAccountId)) || (c.projectId && !projects.has(c.projectId))) fail('Unknown goal association');
  for(const a of w.allocations) if(!(a.targetType === 'claim' ? claims : buckets).has(a.targetId)) fail('Unknown allocation target');
  for(const c of w.cycles) if(c.start >= c.end) fail('Invalid cycle boundary');
});
