import type { StewardState } from "./steward-types";

const isoOffset = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
};

export function createDemoState(
  name = "Alex Morgan",
  email = "demo@steward.local",
): StewardState {
  return {
    version: 1,
    profile: {
      name,
      email,
      currency: "USD",
      nextPayday: isoOffset(8),
      payFrequency: "Biweekly",
      takeHomePay: 3_240,
      minimumBuffer: 1_000,
      riskTolerance: "Balanced",
      budgetingStyle: "Paycheck plan",
      theme: "light",
      onboardingComplete: true,
    },
    accounts: [
      {
        id: "checking-1",
        name: "Everyday checking",
        institution: "Mercury Community",
        type: "Checking",
        balance: 4_860,
        available: 4_742,
        source: "plaid",
        status: "connected",
        lastSynced: "12 minutes ago",
      },
      {
        id: "savings-1",
        name: "High-yield savings",
        institution: "Northstar Bank",
        type: "Savings",
        balance: 8_420,
        available: 8_420,
        source: "plaid",
        status: "connected",
        lastSynced: "12 minutes ago",
      },
      {
        id: "card-1",
        name: "Travel card",
        institution: "Arc",
        type: "Credit card",
        balance: 2_680,
        available: 7_320,
        creditLimit: 10_000,
        interestRate: 22.49,
        minimumPayment: 85,
        dueDate: isoOffset(6),
        source: "manual",
        status: "manual",
        lastSynced: "Updated yesterday",
      },
      {
        id: "invest-1",
        name: "Retirement",
        institution: "Vanguard",
        type: "Investment",
        balance: 24_760,
        available: 0,
        source: "manual",
        status: "manual",
        lastSynced: "Updated Jul 1",
      },
    ],
    transactions: [
      {
        id: "t1",
        accountId: "checking-1",
        merchant: "Northwind Payroll",
        description: "Direct deposit",
        amount: 3_240,
        date: isoOffset(-6),
        category: "Paycheck",
        type: "income",
        confidence: 1,
      },
      {
        id: "t2",
        accountId: "checking-1",
        merchant: "Oak & Main Properties",
        description: "July rent",
        amount: 1_650,
        date: isoOffset(-5),
        category: "Housing",
        type: "expense",
        recurring: true,
        confidence: 1,
      },
      {
        id: "t3",
        accountId: "card-1",
        merchant: "Whole Foods",
        description: "Weekly groceries",
        amount: 86.42,
        date: isoOffset(-2),
        category: "Groceries",
        type: "expense",
        confidence: 0.98,
      },
      {
        id: "t4",
        accountId: "card-1",
        merchant: "Juniper Coffee",
        description: "Coffee and breakfast",
        amount: 14.8,
        date: isoOffset(-1),
        category: "Dining",
        type: "expense",
        confidence: 0.97,
      },
      {
        id: "t5",
        accountId: "card-1",
        merchant: "Amazon",
        description: "Amazon.com purchase",
        amount: 127.36,
        date: isoOffset(-3),
        category: "Uncategorized",
        type: "expense",
        confidence: 0.42,
        needsReview: true,
      },
      {
        id: "t6",
        accountId: "checking-1",
        merchant: "Shell",
        description: "Fuel",
        amount: 48.15,
        date: isoOffset(-4),
        category: "Transportation",
        type: "expense",
        confidence: 0.99,
      },
      {
        id: "t7",
        accountId: "card-1",
        merchant: "Netflix",
        description: "Monthly plan",
        amount: 22.99,
        date: isoOffset(-8),
        category: "Entertainment",
        type: "expense",
        recurring: true,
        confidence: 1,
      },
      {
        id: "t8",
        accountId: "checking-1",
        merchant: "Arc Card",
        description: "Card payment",
        amount: 450,
        date: isoOffset(-10),
        category: "Debt payments",
        type: "expense",
        confidence: 1,
      },
      {
        id: "t9",
        accountId: "card-1",
        merchant: "Municipal Golf",
        description: "Range balls",
        amount: 24,
        date: isoOffset(-7),
        category: "Hobbies",
        type: "expense",
        tags: ["golf"],
        confidence: 0.94,
      },
      {
        id: "t10",
        accountId: "card-1",
        merchant: "Field Notes Books",
        description: "Designing Data-Intensive Applications",
        amount: 52,
        date: isoOffset(-12),
        category: "Education",
        type: "expense",
        tags: ["books", "career"],
        confidence: 0.88,
      },
    ],
    bills: [
      {
        id: "b1",
        name: "Travel card minimum",
        amount: 85,
        dueDate: isoOffset(6),
        frequency: "monthly",
        autopay: true,
        essential: true,
        accountId: "checking-1",
      },
      {
        id: "b2",
        name: "Electric",
        amount: 118,
        dueDate: isoOffset(3),
        frequency: "monthly",
        autopay: true,
        essential: true,
        accountId: "checking-1",
      },
      {
        id: "b3",
        name: "Internet",
        amount: 74,
        dueDate: isoOffset(5),
        frequency: "monthly",
        autopay: true,
        essential: true,
        accountId: "checking-1",
      },
      {
        id: "b4",
        name: "Car insurance",
        amount: 146,
        dueDate: isoOffset(12),
        frequency: "monthly",
        autopay: true,
        essential: true,
        accountId: "checking-1",
      },
      {
        id: "b5",
        name: "Annual cloud storage",
        amount: 119,
        dueDate: isoOffset(19),
        frequency: "annual",
        autopay: false,
        essential: false,
        accountId: "card-1",
      },
    ],
    goals: [
      {
        id: "g1",
        name: "Emergency fund",
        type: "Emergency fund",
        target: 15_000,
        current: 8_420,
        targetDate: isoOffset(240),
        priority: "High",
        status: "Active",
        recommendedContribution: 350,
      },
      {
        id: "g2",
        name: "Clear travel card",
        type: "Debt payoff",
        target: 2_680,
        current: 900,
        targetDate: isoOffset(150),
        priority: "High",
        status: "Active",
        recommendedContribution: 500,
      },
      {
        id: "g3",
        name: "Spring trip",
        type: "Travel",
        target: 2_400,
        current: 620,
        targetDate: isoOffset(280),
        priority: "Medium",
        status: "Active",
        recommendedContribution: 140,
      },
    ],
    projects: [
      {
        id: "p1",
        name: "Apartment reset",
        description: "Make the apartment calmer and more useful.",
        category: "Home",
        priority: "High",
        status: "Active",
        targetDate: isoOffset(90),
        estimatedCost: 1_180,
        actualCost: 310,
        progress: 32,
        nextAction: "Measure the office window for film",
        tasks: [
          { id: "pt1", title: "Refinish desk", complete: true },
          { id: "pt2", title: "Install window film", complete: false },
          { id: "pt3", title: "Choose bookshelf", complete: false },
        ],
      },
      {
        id: "p2",
        name: "Golf practice setup",
        description: "Practice consistently without buying everything at once.",
        category: "Hobby",
        priority: "Medium",
        status: "Active",
        targetDate: isoOffset(120),
        estimatedCost: 1_540,
        actualCost: 120,
        progress: 14,
        nextAction: "Buy the hitting mat after next payday",
        tasks: [
          { id: "pt4", title: "Choose net", complete: true },
          { id: "pt5", title: "Compare hitting mats", complete: false },
        ],
      },
      {
        id: "p3",
        name: "Sharper work wardrobe",
        description: "A compact rotation that fits well.",
        category: "Wardrobe",
        priority: "Medium",
        status: "Planned",
        targetDate: isoOffset(160),
        estimatedCost: 900,
        actualCost: 90,
        progress: 10,
        nextAction: "Take two pairs of pants to the tailor",
        tasks: [
          { id: "pt6", title: "Audit current wardrobe", complete: true },
          { id: "pt7", title: "Tailor pants", complete: false },
        ],
      },
    ],
    wishlist: [
      {
        id: "w1",
        name: "Window film kit",
        projectId: "p1",
        category: "Home",
        priority: "High",
        price: 68,
        desiredDate: isoOffset(10),
        safeDate: isoOffset(0),
        status: "Recommended now",
        reason:
          "It fits this cycle’s project fund and keeps the protected buffer intact.",
      },
      {
        id: "w2",
        name: "Premium golf net",
        projectId: "p2",
        category: "Hobby",
        priority: "Medium",
        price: 420,
        desiredDate: isoOffset(20),
        safeDate: isoOffset(24),
        status: "Wait",
        reason:
          "Buying now would crowd out the planned extra card payment. Recheck after the next paycheck.",
      },
      {
        id: "w3",
        name: "Two tailored shirts",
        projectId: "p3",
        category: "Wardrobe",
        priority: "Medium",
        price: 180,
        desiredDate: isoOffset(30),
        safeDate: isoOffset(8),
        status: "Planned",
        reason:
          "Affordable next cycle after the annual cloud renewal is reserved.",
      },
      {
        id: "w4",
        name: "Design systems book set",
        category: "Education",
        priority: "Low",
        price: 96,
        desiredDate: isoOffset(40),
        safeDate: isoOffset(16),
        status: "Considering",
        reason: "Useful, but lower priority than the apartment and debt goals.",
      },
    ],
    recommendations: [
      {
        id: "r1",
        title: "Send $415 extra to your travel card",
        description:
          "You can accelerate the payoff without touching your protected checking buffer.",
        type: "debt",
        priority: "now",
        impact: 415,
        confidence: 0.94,
        reason:
          "Bills through payday are covered, and your available cash remains above $1,000.",
        action: "Add to paycheck plan",
        status: "active",
      },
      {
        id: "r2",
        title: "Buy the window film kit",
        description:
          "This is the best low-cost project move available in the current cycle.",
        type: "spend",
        priority: "soon",
        impact: 68,
        confidence: 0.91,
        reason:
          "High-priority project, low cost, and no conflict with bills or savings.",
        action: "Mark as planned",
        status: "active",
      },
      {
        id: "r3",
        title: "Clarify the $127 Amazon purchase",
        description:
          "Categorizing it will make your safe-to-spend estimate more accurate.",
        type: "review",
        priority: "soon",
        impact: 127,
        confidence: 1,
        reason: "The merchant is ambiguous and no matching rule exists.",
        action: "Review transaction",
        status: "active",
      },
    ],
    paycheckPlan: {
      date: isoOffset(8),
      expected: 3_240,
      actual: 0,
      savings: 350,
      debt: 500,
      groceries: 260,
      transportation: 120,
      dining: 100,
      buffer: 250,
      projects: 150,
    },
    budgets: [
      {
        id: "bu1",
        category: "Groceries",
        planned: 520,
        actual: 356,
        cadence: "Monthly",
        essential: true,
      },
      {
        id: "bu2",
        category: "Dining",
        planned: 240,
        actual: 188,
        cadence: "Monthly",
        essential: false,
      },
      {
        id: "bu3",
        category: "Projects",
        planned: 300,
        actual: 196,
        cadence: "Monthly",
        essential: false,
      },
      {
        id: "bu4",
        category: "Transportation",
        planned: 240,
        actual: 164,
        cadence: "Monthly",
        essential: true,
      },
    ],
    memories: [
      {
        id: "m1",
        label: "Checking buffer",
        value: "Keep at least $1,000 available in checking.",
        category: "Rule",
      },
      {
        id: "m2",
        label: "Advice style",
        value: "Be direct and give one clear next action.",
        category: "Preference",
      },
      {
        id: "m3",
        label: "Current priority",
        value: "Pay down the travel card while improving the apartment slowly.",
        category: "Priority",
      },
      {
        id: "m4",
        label: "Amazon handling",
        value: "Always ask what an Amazon purchase was before categorizing it.",
        category: "Rule",
      },
    ],
    reviews: [
      {
        id: "rev1",
        period: "This week",
        type: "weekly",
        income: 3_240,
        spending: 2_011,
        savingsChange: 350,
        debtChange: -450,
        wins: [
          "Covered rent without dipping into savings",
          "Stayed under the dining plan",
          "Made an extra card payment",
        ],
        focus: "Clarify Amazon spending and leave the golf net for next cycle.",
      },
      {
        id: "rev2",
        period: "July",
        type: "monthly",
        income: 6_480,
        spending: 4_520,
        savingsChange: 620,
        debtChange: -710,
        wins: [
          "Net position improved by $1,330",
          "Emergency fund passed the halfway point",
          "Finished the desk refinishing task",
        ],
        focus: "Keep discretionary projects below $300 while the card APR is high.",
      },
    ],
    notifications: [
      {
        id: "n1",
        title: "Electric bill in 3 days",
        body: "$118 is already included in your protected cash.",
        time: "Today",
        read: false,
        type: "bill",
      },
      {
        id: "n2",
        title: "A project purchase is safe",
        body: "The $68 window film kit fits your current plan.",
        time: "Today",
        read: false,
        type: "recommendation",
      },
      {
        id: "n3",
        title: "Emergency fund milestone",
        body: "You are now 56% of the way to your target.",
        time: "Yesterday",
        read: true,
        type: "goal",
      },
    ],
    notificationPreferences: {
      bills: true,
      payday: true,
      recommendations: true,
      unusualSpending: true,
      weeklyReview: true,
      monthlyReview: true,
      marketing: false,
    },
  };
}
